--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "DEMO"."CATEGORY"
   (	"NO" NUMBER,
	"TITLE" VARCHAR2(50 BYTE) DEFAULT ''
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATEGORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."CATEGORY_PK" ON "DEMO"."CATEGORY" ("NO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "DEMO"."CATEGORY" ADD CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEMO"."CATEGORY" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."CATEGORY" MODIFY ("NO" NOT NULL ENABLE);

-- 시퀀스
CREATE SEQUENCE CATEGORY_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1;


-- 데이터
Insert into DEMO.CATEGORY (NO,TITLE) values (CATEGORY_SEQ.nextval,'hotel');
Insert into DEMO.CATEGORY (NO,TITLE) values (CATEGORY_SEQ.nextval,'school');
Insert into DEMO.CATEGORY (NO,TITLE) values (CATEGORY_SEQ.nextval,'cafe');
Insert into DEMO.CATEGORY (NO,TITLE) values (CATEGORY_SEQ.nextval,'shop');
Insert into DEMO.CATEGORY (NO,TITLE) values (CATEGORY_SEQ.nextval,'park');
Insert into DEMO.CATEGORY (NO,TITLE) values (CATEGORY_SEQ.nextval,'hospital');
commit;
