--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

CREATE TABLE "DEMO"."LOCATION"
(	"NO" NUMBER,
     "DISTRICT" VARCHAR2(50 BYTE) DEFAULT '',
     "CITY" VARCHAR2(300 BYTE)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOCATION_PK
--------------------------------------------------------

CREATE UNIQUE INDEX "DEMO"."LOCATION_PK" ON "DEMO"."LOCATION" ("NO")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

ALTER TABLE "DEMO"."LOCATION" MODIFY ("CITY" NOT NULL ENABLE);
ALTER TABLE "DEMO"."LOCATION" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("NO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "DEMO"."LOCATION" MODIFY ("DISTRICT" NOT NULL ENABLE);
ALTER TABLE "DEMO"."LOCATION" MODIFY ("NO" NOT NULL ENABLE);


-- 시퀀스
CREATE SEQUENCE LOCATION_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1;

-- 데이터
