--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "DEMO"."MEMBER"
   (	"NO" NUMBER,
	"ID" VARCHAR2(50 BYTE),
	"PASSWORD" VARCHAR2(256 BYTE),
	"NAME" VARCHAR2(20 BYTE),
	"EMAIL" VARCHAR2(100 BYTE),
	"HP" VARCHAR2(20 BYTE),
	"BOOKING_COUNT" NUMBER DEFAULT 0,
	"STATE" VARCHAR2(10 BYTE) DEFAULT 'Y',
	"ROLE" VARCHAR2(20 BYTE) DEFAULT 'BUYER'
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DEMO"."MEMBER"."NO" IS '인덱스';
   COMMENT ON COLUMN "DEMO"."MEMBER"."ID" IS '아이디';
   COMMENT ON COLUMN "DEMO"."MEMBER"."PASSWORD" IS '비밀번호';
   COMMENT ON COLUMN "DEMO"."MEMBER"."NAME" IS '성함';
   COMMENT ON COLUMN "DEMO"."MEMBER"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "DEMO"."MEMBER"."HP" IS '휴대폰번호';
   COMMENT ON COLUMN "DEMO"."MEMBER"."BOOKING_COUNT" IS '총예약횟수';
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."MEMBER_PK" ON "DEMO"."MEMBER" ("NO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "DEMO"."MEMBER" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEMO"."MEMBER" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."MEMBER" MODIFY ("HP" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."MEMBER" MODIFY ("NO" NOT NULL ENABLE);
