CREATE TABLE MEMBER
(
  NO NUMBER NOT NULL
, ID VARCHAR2(50) NOT NULL
, PASSWORD VARCHAR2(100) NOT NULL
, NAME VARCHAR2(20) NOT NULL
, EMAIL VARCHAR2(100) NOT NULL
, HP VARCHAR2(20) NOT NULL
, BOOKING_COUNT NUMBER DEFAULT 0
, STATE VARCHAR2(10) DEFAULT 'Y' NOT NULL
, CONSTRAINT MEMBER_PK PRIMARY KEY
  (
    NO
  )
  ENABLE
);

COMMENT ON COLUMN MEMBER.NO IS '인덱스';

COMMENT ON COLUMN MEMBER.ID IS '아이디';

COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호';

COMMENT ON COLUMN MEMBER.NAME IS '성함';

COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER.HP IS '휴대폰번호';

COMMENT ON COLUMN MEMBER.BOOKING_COUNT IS '총예약횟수';
