
  CREATE TABLE "DEMO"."SHOP" 
   (	"NO" NUMBER NOT NULL ENABLE, 
	"COMPANY_OWNER" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	"COMPANY_NAME" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	"SAUPJA_NO" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	"COMPANY_TEL" VARCHAR2(225 BYTE), 
	"COMPANY_ZIP" VARCHAR2(225 BYTE), 
	"COMPANY_ADDR" VARCHAR2(225 BYTE), 
	"BANK_NAME" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	"BANK_NUMBER" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	"BANK_OWNER_NAME" VARCHAR2(225 BYTE) NOT NULL ENABLE, 
	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"CATEGORY_NO" NUMBER NOT NULL ENABLE, 
	"LOCATION_NO" NUMBER NOT NULL ENABLE, 
	"MAIN_FILE" VARCHAR2(300 BYTE), 
	"SUB_FILE" VARCHAR2(300 BYTE), 
	 CONSTRAINT "SHOP_PK" PRIMARY KEY ("NO", "MEMBER_NO", "CATEGORY_NO", "LOCATION_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DEMO"."SHOP"."NO" IS '상점번호';
   COMMENT ON COLUMN "DEMO"."SHOP"."COMPANY_OWNER" IS '대표자명';
   COMMENT ON COLUMN "DEMO"."SHOP"."COMPANY_NAME" IS '상호명';
   COMMENT ON COLUMN "DEMO"."SHOP"."SAUPJA_NO" IS '사업자번호';
   COMMENT ON COLUMN "DEMO"."SHOP"."COMPANY_TEL" IS '사업장 전화번호';
   COMMENT ON COLUMN "DEMO"."SHOP"."COMPANY_ZIP" IS '사업장 우편번호';
   COMMENT ON COLUMN "DEMO"."SHOP"."COMPANY_ADDR" IS '사업장 주소';
   COMMENT ON COLUMN "DEMO"."SHOP"."BANK_NAME" IS '은행';
   COMMENT ON COLUMN "DEMO"."SHOP"."BANK_NUMBER" IS '계좌번호';
   COMMENT ON COLUMN "DEMO"."SHOP"."BANK_OWNER_NAME" IS '예금주';
   COMMENT ON COLUMN "DEMO"."SHOP"."MEMBER_NO" IS '멤버번호';
   COMMENT ON COLUMN "DEMO"."SHOP"."CATEGORY_NO" IS '운영샵 카테고리';
   COMMENT ON COLUMN "DEMO"."SHOP"."LOCATION_NO" IS '지역번호';
   COMMENT ON COLUMN "DEMO"."SHOP"."MAIN_FILE" IS '메인이미지';
   COMMENT ON COLUMN "DEMO"."SHOP"."SUB_FILE" IS '서브이미지';



-- 시퀀스

   CREATE SEQUENCE  "DEMO"."SHOP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER  NOCYCLE ;

