-- 테이블생성
CREATE TABLE SHOP_ITEM 
(
  IT_NO NUMBER NOT NULL 
, SHOP_NO NUMBER NOT NULL 
, IT_NAME VARCHAR2(225 BYTE) NOT NULL 
, IT_BRAND VARCHAR2(225 BYTE) 
, IT_CATEGORY VARCHAR2(225 BYTE) 
, IT_EXPLAN_TEXT VARCHAR2(225 BYTE) 
, CUST_PRICE NUMBER 
, PRICE NUMBER NOT NULL 
, SAVE_MONEY NUMBER 
, SHIPPING_CHARGE NUMBER 
, MAIN_FILE VARCHAR2(225 BYTE) NOT NULL 
, SUB_FILE VARCHAR2(225 BYTE) 
, MAIN_REAL_FILE VARCHAR2(300 BYTE) 
, SUB_REAL_FILE VARCHAR2(300 BYTE) 
, CONSTRAINT SHOP_ITEM_PK PRIMARY KEY 
  (
    IT_NO 
  , SHOP_NO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SHOP_ITEM_PK ON SHOP_ITEM (IT_NO ASC, SHOP_NO ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

COMMENT ON COLUMN SHOP_ITEM.IT_NO IS '상품번호,seq';

COMMENT ON COLUMN SHOP_ITEM.SHOP_NO IS 'SHOP번호';

COMMENT ON COLUMN SHOP_ITEM.IT_NAME IS '상품명';

COMMENT ON COLUMN SHOP_ITEM.IT_BRAND IS '브랜드명';

COMMENT ON COLUMN SHOP_ITEM.IT_CATEGORY IS '상품 카테고리';

COMMENT ON COLUMN SHOP_ITEM.IT_EXPLAN_TEXT IS '상품설명글';

COMMENT ON COLUMN SHOP_ITEM.CUST_PRICE IS '기존가격';

COMMENT ON COLUMN SHOP_ITEM.PRICE IS '판매가격';

COMMENT ON COLUMN SHOP_ITEM.SAVE_MONEY IS '적립금';

COMMENT ON COLUMN SHOP_ITEM.SHIPPING_CHARGE IS '배송비';

COMMENT ON COLUMN SHOP_ITEM.MAIN_FILE IS '메인이미지';

COMMENT ON COLUMN SHOP_ITEM.SUB_FILE IS '상세이미지';

COMMENT ON COLUMN SHOP_ITEM.MAIN_REAL_FILE IS '메인이미지파일이름';

COMMENT ON COLUMN SHOP_ITEM.SUB_REAL_FILE IS '상세페이지파일이름';


-- 시퀀스
CREATE SEQUENCE ITEM_SEQ INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20 ORDER;

-- 더미


